version: '3.4'

services:
  mentorsservice:
    build: 
      context: .
      dockerfile: MentorsService-Dockerfile
    ports: 
      - '8000:80'
    image: mentorsservice
  clientsservice:
    build: 
      context: .
      dockerfile: ClientsService-Dockerfile
    ports:
      - '8001:80'
    image: clientsservice
