version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: OUTSIDE://:9092,INSIDE://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://192.168.0.13:9092,INSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      #topic name:partitions:replicates
      KAFKA_CREATE_TOPICS: "tasks-run:1:1,tasks-result:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  mentorsservice:
    build: 
      context: .
      dockerfile: MentorsService-Dockerfile
    ports: 
      - '8000:80'
    image: mentorsservice
  clientsservice:
    build: 
      context: .
      dockerfile: ClientsService-Dockerfile
    ports:
      - '8001:80'
    image: clientsservice
